version: "3.8"
services:
  www:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./dist/www:/usr/share/nginx/html:ro
    ports:
    - "22592:80"
  api:
    image: node
    volumes:
    - ./dist/api:/usr/src/app:ro
    - data:/usr/src/data
    working_dir: /usr/src/app
    command: node .
    hostname: api

volumes:
  data:
